services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-mkdocs
    ports:
      - "8000:8000"
    volumes:
      - .:/site
    command: mkdocs serve -a 0.0.0.0:8000
